name: Deploy lambda

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  LAMBDA_FUNCTION_NAME: check-nolnol-backend-lambda

jobs:
  deploy:
    environment: main
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Poetry 1.3.1
        run: pipx install poetry==1.3.1

      - name: Install Poetry dependencies
        run: poetry install

      - name: Export requirements.txt
        run: poetry export --format requirements.txt --output requirements.txt

      - name: Install requirements dependencies
        run: pip install --target ./package --requirement requirements.txt

      - name: Zip deployment package
        run: |
          cd ./package
          zip -r ../deployment-package.zip .
          cd ..
          zip -r deployment-package.zip ./app

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy package
        run: aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --zip-file fileb://deployment-package.zip
